# Environment Settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Project Settings
modDisplayName=TslatEntityStatus
modId=tslatentitystatus
group=net.tslat

# Project Properties
modLicense=MPL-2.0
modAuthors=Tslat
modDescription=View entity health and other statuses. Make smacking things fun again!

# Links
modHomepage=https://www.curseforge.com/minecraft/mc-mods/tslatentitystatus-tes
modGitRepo=https://github.com/Tslat/TslatEntityStatus
modIssuesTracker=https://github.com/Tslat/TslatEntityStatus/issues

# Publishing
modrinthProjectId=4A86JsDZ
curseforgeProjectId=830420